// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataNormalization.Models;

/// <summary>
/// Used to create templates for individual, searchable fields for an item.
/// </summary>
public partial class EquipmentService_ItemInfoTemplate
{
    public int TemplateId { get; set; }

    public string TemplateName { get; set; }

    public string TemplateDescription { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string FieldName1 { get; set; }

    public string FieldName2 { get; set; }

    public string FieldName3 { get; set; }

    public string FieldName4 { get; set; }

    public string FieldName5 { get; set; }

    public string FieldName6 { get; set; }

    public string FieldName7 { get; set; }

    public string FieldName8 { get; set; }

    public string FieldName9 { get; set; }

    public string FieldName10 { get; set; }

    public virtual ICollection<EquipmentService_ItemInfoTemplateValues> EquipmentService_ItemInfoTemplateValues { get; set; } = new List<EquipmentService_ItemInfoTemplateValues>();
}