// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataNormalization.Models;

public partial class EquipmentService_ItemDimensions
{
    public int DimensionId { get; set; }

    public int UomId { get; set; }

    public decimal Length { get; set; }

    public decimal Width { get; set; }

    public decimal Height { get; set; }

    public virtual ICollection<EquipmentService_ItemInfo> EquipmentService_ItemInfo { get; set; } = new List<EquipmentService_ItemInfo>();

    public virtual EquipmentService_DimensionsUom Uom { get; set; }
}