// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataNormalization.Models;

public partial class EquipmentService_ItemInfoTemplateValues
{
    public int ItemInfoId { get; set; }

    public int TemplateId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime DateCreated { get; set; }

    public string FieldValue1 { get; set; }

    public string FieldValue2 { get; set; }

    public string FieldValue3 { get; set; }

    public string FieldValue4 { get; set; }

    public string FieldValue5 { get; set; }

    public string FieldValue6 { get; set; }

    public string FieldValue7 { get; set; }

    public string FieldValue8 { get; set; }

    public string FieldValue9 { get; set; }

    public string FieldValue10 { get; set; }

    public virtual EquipmentService_ItemInfo ItemInfo { get; set; }

    public virtual EquipmentService_ItemInfoTemplate Template { get; set; }
}