// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataNormalization.Models;

/// <summary>
/// Table that contains the information specific about an item.
/// </summary>
public partial class EquipmentService_ItemInfo
{
    public int ItemInfoId { get; set; }

    public string PartNumber { get; set; }

    public string Description { get; set; }

    public string Manufacturer { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string Uom { get; set; }

    public decimal? Weight { get; set; }

    public string WeightUnit { get; set; }

    public int? DimensionId { get; set; }

    public int? lifecycleId { get; set; }

    public decimal? ListPrice { get; set; }

    public virtual EquipmentService_ItemDimensions Dimension { get; set; }

    public virtual EquipmentService_ItemInfoTemplateValues EquipmentService_ItemInfoTemplateValues { get; set; }

    public virtual ICollection<EquipmentService_VendorPrices> EquipmentService_VendorPrices { get; set; } = new List<EquipmentService_VendorPrices>();

    public virtual tblManufacturers ManufacturerNavigation { get; set; }

    public virtual Item_LifeCycles lifecycle { get; set; }
}