// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataNormalization.Models;

public partial class EquipmentService_DimensionsUom
{
    public int UomId { get; set; }

    public string Uom { get; set; }

    public string Name { get; set; }

    public virtual ICollection<EquipmentService_ItemDimensions> EquipmentService_ItemDimensions { get; set; } = new List<EquipmentService_ItemDimensions>();
}