// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataNormalization.Models;

public partial class EquipmentService_VendorPrices
{
    public int PriceId { get; set; }

    public int ItemId { get; set; }

    public int VendorId { get; set; }

    public DateTime LastUpdated { get; set; }

    public DateTime? DeletedDate { get; set; }

    public decimal MSRP { get; set; }

    public decimal OurPrice { get; set; }

    public bool? PrimaryVendor { get; set; }

    public virtual EquipmentService_ItemInfo Item { get; set; }

    public virtual VENDORS Vendor { get; set; }
}