// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataNormalization.Models;

public partial class tblManufacturers
{
    public int ID { get; set; }

    public string ManfName { get; set; }

    public string Primary { get; set; }

    public bool? AuthorizedDistributor { get; set; }

    public virtual ICollection<EquipmentService_ItemInfo> EquipmentService_ItemInfo { get; set; } = new List<EquipmentService_ItemInfo>();
}