// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataNormalization.Models;

public partial class VENDORS
{
    public int VendorID { get; set; }

    public string Vendor { get; set; }

    public string Contact { get; set; }

    public string Address { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Country { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Comments { get; set; }

    public string RMAReqd { get; set; }

    public DateTime? DateAdded { get; set; }

    public string Email { get; set; }

    public DateTime? LastPoDate { get; set; }

    public string Approved { get; set; }

    public string RepAppr { get; set; }

    public string RepApprDate { get; set; }

    public string RepApprBy { get; set; }

    public string MfgAppr { get; set; }

    public string MfgApprDate { get; set; }

    public string MfgApprBy { get; set; }

    public string RepDNU { get; set; }

    public string RepDNUDate { get; set; }

    public string RepDNUBy { get; set; }

    public string MfgDNU { get; set; }

    public string MfgDNUDate { get; set; }

    public string MfgDNUBy { get; set; }

    public string Website { get; set; }

    public int? currencyId { get; set; }

    public string accountingId { get; set; }

    public string Terms { get; set; }

    public int? VendorTypeId { get; set; }

    public decimal? CreditLimit { get; set; }

    public string Alias { get; set; }

    public DateTime? DeletedDate { get; set; }

    /// <summary>
    /// This is the vendor&apos;s internal account number for us in their system (their key for us)
    /// </summary>
    public string VendorAccountNumber { get; set; }

    public virtual ICollection<EquipmentService_VendorPrices> EquipmentService_VendorPrices { get; set; } = new List<EquipmentService_VendorPrices>();
}